### ISSUE TITLE
Clip Cursor

### ISSUE THREAD

**Issue by Stateford** [20k/game_window_manager#5]
Author of [display lock](https://github.com/idietmoran/Display-Lock) here. I would like to work on the locking the cursor to the window.

I suggest storing the the selected applications hWnd to the struct, and comparing the foreground window and locking if the selected window is in focus.

I also suggest doing this in a separate thread for better performance, and so it doesn't block from the main application, which is what I did in display lock.

Let me know what you think.

**Comment by Stateford** [comment]
https://github.com/idietmoran/Clip-Window

a dynamic link library to lock the cursor to the specified window in a separate thread. Will only lock if window is focus. This should make life easier for you, all that's left is the logic of when to stop it.

**Comment by 20k** [comment]
Hi there

Locking the cursor only when in focus seems like a good plan, I will start working on this soon. Is GetForegroundWindow() an expensive enough call that it is necessary to use a separate thread to maintain consistent performance in the main application? I'd been planning to use it to implement detection for triggering an application profile instead of needing a refresh on f9

If it is an expensive call, a different approach might be necessary as the application will cause cpu spikes that could affect game performance, which is a core development goal

Thanks!

**Comment by Stateford** [comment]
No it's not. You can run it yourself. I used it in Display Lock and the CPU never goes above 0.5%. I keep it in another thread to prevent blocking the main thread, and it will end when the `.stop()` method is called.
